version: "3.9"

services:
  db:
    image: postgres:15
    container_name: himera-db
    restart: always
    environment:
      POSTGRES_USER: himera
      POSTGRES_PASSWORD: himera
      POSTGRES_DB: himera
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: himera-redis
    restart: always
    ports:
      - "6380:6379"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: himera-bot-app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      APP_ENV: development
      HTTP_PORT: "8080"
      LOG_LEVEL: info
    ports:
      - "8080:8080"

volumes:
  db_data:
